springdoc:
  version: 1.1
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger.html
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  server:
    port: 9090

  keycloak:
    auth-server-url: http://localhost:8080/
    realm: keycloak
    resource: springboot-keycloak
    public-client: true
    bearer-only: true